config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  # products
  resources :products do
    resources :reviews, except: [:index, :show]
  end

  root 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

 validates :name, :description, :price, :presence => true

 has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
   validates_confirmation_of :password
   validates :email, :presence => true, :uniqueness => true
   before_save :encrypt_password

   def encrypt_password
     self.password_salt = BCrypt::Engine.generate_salt
     self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
   end

   def self.authenticate(email, password)
     user = User.find_by "email = ?", email
     if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
       user
     else
       nil
     end
   end

   def is_admin?
     self.email == "admin@admin"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :is_admin?

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end

  def authorize_admin
    if !is_admin?
      flash[:alert] = "You need to be admin to perform this action!"
      redirect_to '/'
    end
  end


  def is_admin?
    current_user != nil && current_user.is_admin?
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :authorize_admin, except: [:index, :show]

 def index
   @products = Product.all
 end

 def show
   @product = Product.find(params[:id])
 end

 def new
   @product = Product.new
 end

 def create
   @product = Product.new(product_params)
   if @product.save
     redirect_to products_path,  notice: "Product successfully added!"
   else
     render :new
   end
 end

 def edit
   @product = Product.find(params[:id])
 end

 def update
   @product = Product.find(params[:id])
   if @product.update(product_params)
     redirect_to product_path(@product), notice: "Product successfully updated!"
   else
     render :edit
   end
 end

 def destroy
   @product = Product.find(params[:id])
   @product.reviews do |review|
     review.destroy
   end
   @product.destroy
   redirect_to products_path
 end

 private

 def product_params
   params.require(:product).permit(:name, :description, :price)
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:new, :create]
  before_action :authorize_admin, only: [:destroy]

  def new
   @product = Product.find(params[:product_id])
   @new_review = @product.reviews.new
 end

 def create
   @product = Product.find(params[:product_id])
   @new_review = @product.reviews.new(review_params)
   if @new_review.save
     redirect_to @product, notice: "Review successfully added!"
   else
     render :new
   end
 end

 def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

 private

 def review_params
   params.require(:review).permit(:content, :author, :product_id)
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.authenticate(params[:user][:email], params[:user][:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      @user = User.new
      @user.errors.add :email, 'Email or password incorrect'
      @user.errors.add :password, 'Email or password incorrect'
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/index.html.erb
<div class="container">

  <div class="starter-template">
    <h1>Perfect furniture for perfect home</h1>
    <p class="lead">Create the home you love every day.</p>
    <img id="landing" src="https://www.onekingslane.com/text/content/about_us/assets/about-us-background.png" alt="">
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallBusiness</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Queen's Lane</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>  <%= link_to "Products", products_path %></li>
          </ul>
          <span class="navbar-right navbar-text">
            <% if current_user %>
              <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
            <% else %>
              <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
            <% end %>
          </span>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for [@product], url: products_path do |form| %>
  <%= form.input :name %>
  <%= form.input :description %>
  <%= form.input :price %>
  <%= form.button :submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= simple_form_for [@product], url: product_path do |form| %>
  <%= form.input :name%>
  <%= form.input :description%>
  <%= form.input :price%>

  <%= form.submit class: 'btn btn-success'%>
<% end %>

app/views/products/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row">
      <% if is_admin? %>
      <div class="btn btn-default">
        <%= link_to "Add Product", new_product_path %>
      </div>
      <% end %>
      <% @products.each do |product|  %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to product do %>
              <b><%= product.name %></b>
            <% end %>
          </div>
          <div class="panel-body">
            <p> <%= product.description %></p>
            <p> <%= number_to_currency(product.price) %> </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h3><%= @product.name  %></h3>
<h5><%= @product.description %></h5>
<h6><%= number_to_currency(@product.price) %></h6>

<% if is_admin? %>
  <%= link_to 'Edit Product', edit_product_path, :class => 'btn btn-success btn-sm'  %>
  <%= link_to 'Delete Product', @product, :method =>'delete', :data => {:confirm => 'You sure?'}, :class => 'btn btn-danger btn-sm'%>
<% end %>

<h3>Reviews</h3>
<% if @product.reviews.any? %>
    <% @product.reviews.each do |review| %>
      <p><%= review.author %> said <%= review.content %>
        <% if is_admin? %>
          <%= link_to(product_review_path(@product, review), :method => 'delete')  do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </p>
    <% end %>

<% else %>
  <p>No reviews yet</p>
<% end %>

<% if current_user %>
<%= link_to 'Add Review', new_product_review_path(@product), class: 'btn btn-info btn-sm' %>
<% else %>
<p>Login to add reviews</p>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [@product, @new_review], url: product_reviews_path(@product, @new_review) do |form| %>
  <p>Author: <%= current_user.user_name %> </p>
  <%= form.input :author, :as => :hidden, :input_html => {:value => current_user.user_name} %>
  <%= form.input :content %>
  <%= form.submit class: 'btn btn-success'%>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4">

  </div>
  <div class="col-md-4">
    <h1> Sign up</h1>
    <%= simple_form_for @user do |f| %>
      <%= f.error_notification %>
      <%= f.input :email %>
      <%= f.input :user_name %>
      <%= f.input :password, as: :password %>
      <%= f.input :password_confirmation, as: :password %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>